AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LeetSync Lambda - syncs LeetCode submissions to DynamoDB daily

Globals:
  Function:
    Timeout: 10
    Runtime: java21
    MemorySize: 512

Resources:
  LeetSyncFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LeetSyncFunction
      Handler: com.leetsync.ingestion.handler.SyncHandler::handleRequest
      CodeUri: target/ingestion-lambda-1.0.0.jar
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: AcSubmissions
      Events:
        ScheduledSync:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
